apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongo-uri: mongodb://xquare:mk2EYN34xE9LD9U@xquare-docdb-cluster.cluster-c31jdrca4ayb.ap-northeast-2.docdb.amazonaws.com:27017/tracing?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
